### ISSUE TITLE
Improve anime recognition

### ISSUE THREAD

**Issue by erengy** [erengy/taiga#71]
Version 1.2 is, for the most part, dedicated to improving anime recognition. I'll be using this issue to keep track of what I've done. You can use it to suggest additional improvements.

**Pros:**
- Works significantly faster
- Is much more accurate

**Cons:**
- Increased memory usage (due to normalized title and trigram storage)
- Increased executable size (due to Unicode data storage)

### TODO

- [x] Switch to [Anitomy](https://github.com/erengy/anitomy) for filename parsing
- [x] Refactor anime identification code
- [x] Improve identification performance by storing normalized titles in an associative container
- [x] Improve fuzzy matching
- [x] Handle [canonical equivalence](http://www.unicode.org/notes/tn5/)
- [x] Handle other equivalences (e.g. `2nd Season`, `Season 2`, `S2` → `2`)
- [x] Handle Roman numerals (e.g. `II`, `III`, `IV`, `XIII`)
- [x] Consider transliterating `@` to `a`, and similar characters
- [x] Switch from anime::Episode to anitomy::Elements
- [x] Ignore files with certain keywords (e.g. `ED`, `OP`, `PV`)
- [x] Analyze database for titles where punctuation makes a difference
- [x] Handle the case where fansub groups continue numbering their releases from the last episode of the previous season (e.g. *Mushishi S2*, *Kokoro Connect*, *Aldnoah Zero*, *Jojo*, *Kuroko*, *Shugo Chara*)
- [x] Take directory name into account while looking for anime title (e.g. `D:\Anime\Toradora!\01.mkv`)
- [x] Consider completely switching to file-handle based detection if it's reliable (some features such as *Ignore files outside of root folders* don't work well with other methods)

**Comment by erengy** [comment]
Done! :tada:

**Comment by vendethiel** [comment]
:cake:

**Comment by rr-** [comment]
Great job.
